stages:
  - build
  - test
  - deploy

dev:build:
  stage: build
  needs: [ ]
  image: golang:1.16.3
  script:
    - make build
  except:
    - master
    - tags

dev:lint:
  stage: test
  needs: [ ]
  image: golangci/golangci-lint:v1.39.0
  script:
    - make lint
  except:
    - master
    - tags

dev:unit-test:
  stage: test
  needs: [ ]
  image: golang:1.16.3
  script:
    - make test
  except:
    - master
    - tags

stg:build-image:
  stage: build
  needs: [ ]
  image: docker:20.10.1
  services:
    - docker:20.10.1-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
  except:
    - tags
