kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: grafana2vonage
  labels:
    app: grafana2vonage
spec:
  selector:
    matchLabels:
      app: grafana2vonage
  template:
    metadata:
      labels:
        app: grafana2vonage
    spec:
      imagePullSecrets:
        - name: gitlab
      containers:
        - name: api
          image: registry.gitlab.com/cbiot/backend/grafana2vonage:latest
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: API_KEY
              value: "132f659f"
            - name: API_SECRET
              value: "IE7mXbDBe7WH6jNz"
            - name: FROM
              value: "17052021346"
            - name: TO
              value: "13437776364"

---

apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: grafana2vonage
spec:
  type: ClusterIP
  selector:
    app: grafana2vonage
  ports:
    - port: 8000
      targetPort: 8000
