apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: gitlab
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsidXNlcm5hbWUiOiJuYXNlcm1pcnphZWk4OSIsInBhc3N3b3JkIjoiMjMyMTM2ODkwIiwiZW1haWwiOiJuYXNlcm1pcnphZWk4OUBnbWFpbC5jb20iLCJhdXRoIjoiYm1GelpYSnRhWEo2WVdWcE9EazZNak15TVRNMk9Ea3cifX19
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: grafana2vonage
  labels:
    app: grafana2vonage
spec:
  selector:
    matchLabels:
      app: grafana2vonage
  template:
    metadata:
      labels:
        app: grafana2vonage
    spec:
      imagePullSecrets:
        - name: gitlab
      containers:
        - name: api
          image: registry.gitlab.com/cbiot/backend/grafana2vonage:latest
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: API_KEY
              value: "enter api key"
            - name: API_SECRET
              value: "enter secret api"
            - name: FROM
              value: "17052021300"
            - name: TO
              value: "a number like 1343xxxxxxx"

---

apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: grafana2vonage
spec:
  type: ClusterIP
  selector:
    app: grafana2vonage
  ports:
    - port: 8000
      targetPort: 8000
